### ISSUE TITLE
Run volta-cli Step 404 Error

### ISSUE THREAD

**Issue by pjlamb12** [nrwl/ci#33]
I generated the GitHub Actions CI file with the generator, but when I create the PR for the action to run it fails with the following error:

Agents:

<img width="587" alt="image" src="https://user-images.githubusercontent.com/2006222/196295669-7a188ad7-b1a5-45fe-b9fa-ff1497fca919.png">

Main Job: 

<img width="514" alt="image" src="https://user-images.githubusercontent.com/2006222/196295745-94d7681a-6500-4ef5-8e7f-d1c189bbab59.png">

I'm unsure why it's failing, but my ci.yaml file that was generated is basically unchanged. I added a few environment variables and an init-commands section, and changed the name of the main branch:

<details>
<summary>CI Yaml File</summary>
on:
    push:
        branches:
            - master
    pull_request:
        branches:
            - master

env:
  NX_BRANCH: ${{ github.event.number }}
  NX_RUN_GROUP: ${{ github.run_id }}
  NPM_TOKEN: ${{ secrets.MYGET_TOKEN }}

jobs:
    main:
        name: Nx Cloud - Main Job
        uses: nrwl/ci/.github/workflows/nx-cloud-main.yml@v0.4
        with:
            main-branch-name: master
            init-commands: |
                cp npmrc_file .npmrc
            parallel-commands: |
                npx nx-cloud record -- npx nx workspace-lint
                npx nx-cloud record -- npx nx format:check
            parallel-commands-on-agents: |
                npx nx affected --target=lint --parallel=3
                npx nx affected --target=test --parallel=3 --ci --code-coverage
                npx nx affected --target=build --parallel=3

    agents:
        name: Nx Cloud - Agents
        uses: nrwl/ci/.github/workflows/nx-cloud-agents.yml@v0.4
        with:
            number-of-agents: 3
</details>

My version of Angular is 13.3.11 and Nx is 14.1.9.

**Comment by g-cheishvili** [comment]
Thank you, was creating issue. 
https://github.com/volta-cli/action/issues/117 This is related

**Comment by aautem** [comment]
Opened a PR for this here: https://github.com/nrwl/ci/pull/32

**Comment by JamesHenry** [comment]
This should be resolved in the latest version v0.8

**Comment by pjlamb12** [comment]
@JamesHenry I'm still seeing this in v0.8 today

![image](https://user-images.githubusercontent.com/2006222/198088685-4d771958-6911-4b04-b5f0-6b1a7a6984ce.png)

And this is part of my workflow yaml file:

![image](https://user-images.githubusercontent.com/2006222/198088791-a9782a8b-5d42-4837-840a-d9cf25b4a6e9.png)

**Comment by pjlamb12** [comment]
So it appears that even though I am referencing v0.8 it's trying to use the same volta-cli action.

**Comment by aautem** [comment]
@pjlamb12 Are you also using NX Cloud - Agents?

```
agents:
    name: Nx Cloud - Agents
    uses: nrwl/ci/.github/workflows/nx-cloud-agents.yml@v0.8
    with:
      number-of-agents: 3
```

**Comment by pjlamb12** [comment]
I think I only updated one spot. 🤦🏾‍♂️ I will check this out though.
